---
title: "R Notebook"
output: revealjs::revealjs_presentation
---
# a
```{r,echo=FALSE,message=FALSE,warning=FALSE}
library(tidyverse)
library(plotly)
```

```{r}
cobb_douglas <- function(x, y, A, alpha) {
  A * x ^ alpha * y ^ (1 - alpha)
}

# 予算制約線
bud_con <- function(x, p_x, p_y, I) {
  (I - p_x * x) / p_y
}

# 無差別曲線
indiff_crv <- function(x, U, A, alpha) {
  (U / A * x ^ (-alpha)) ^ (1 / (1 - alpha))
}
```

# test1
```{r,echo=FALSE,message=FALSE,warning=FALSE}
A <- 1
alpha <- 1 / 3

.mesh_grid <- pracma::meshgrid(seq(0, 10, 0.1))
x <- .mesh_grid$X
y <- .mesh_grid$Y
U <- cobb_douglas(x, y, A, alpha)

p_x <- 1
p_y <- 2
I <- 10

x_bud_con <- seq(0, 10, 0.1)
y_bud_con <- bud_con(x_bud_con, p_x, p_y, I)
U_bud_con <- cobb_douglas(x_bud_con, y_bud_con, A, alpha)

U_indiff_crv <- max(U_bud_con)
x_indiff_crv <- seq(0, 10, 0.1)
y_indiff_crv <- indiff_crv(x_indiff_crv, U_indiff_crv, A, alpha)

scene <- list(camera = list(eye = list(x = 1.25, 
                                       y = -1.25, 
                                       z = 1.25)))

plot_ly() %>% 
  add_surface(x = x,
              y = y,
              z = U) %>% 
  add_paths(x = x_bud_con,
            y = y_bud_con,
            z = U_bud_con) %>% 
  add_paths(x = x_indiff_crv,
            y = y_indiff_crv,
            z = U_indiff_crv) %>% 
  layout(scene = scene)
```

